import { useState } from "react";
import type { ReviewChange, ReviewState } from "../api/types";
import { DiffView } from "./DiffView";
type Props = { review: ReviewState | null; busy: boolean; onStart: () => void; onApprove: (id: string) => void; onReject: (id: string, feedback?: string) => void; onRefresh: () => void; docxUrl: string };
function ChangeCard({ change, busy, onApprove, onReject }: { change: ReviewChange; busy: boolean; onApprove: (id: string) => void; onReject: (id: string, feedback?: string) => void }) { const [feedback, setFeedback] = useState(""); return <article className="change-card"><div className="row"><strong>{change.operation} proposal</strong><small>{change.change_id}</small></div><p>{change.ai_explanation ?? "A targeted editorial proposal is ready for review."}</p><DiffView oldHtml={change.old_html} newHtml={change.new_html} /><label>Optional rejection feedback<textarea value={feedback} onChange={(event) => setFeedback(event.target.value)} /></label><div className="actions"><button className="primary" disabled={busy} onClick={() => onApprove(change.change_id)}>{busy ? "Applying approved change…" : "Approve change"}</button><button className="secondary" disabled={busy} onClick={() => onReject(change.change_id, feedback.trim() || undefined)}>Reject change</button></div></article>; }
export function ReviewPanel({ review, busy, onStart, onApprove, onReject, onRefresh, docxUrl }: Props) {
  if (!review) return <section className="review-panel"><span className="eyebrow">Controlled review</span><h2>Review Executive Summary</h2><p>PaperForge asks SuperDocs for one targeted editorial improvement. No change is applied until you approve it.</p><button className="primary" disabled={busy} onClick={onStart}>{busy ? "Preparing review…" : "Review Executive Summary"}</button></section>;
  const counts = `${review.approved_changes.length} approved · ${review.rejected_changes.length} rejected · ${review.pending_changes.length} pending`;
  if (review.status === "awaiting_approval") return <section className="review-panel"><span className="eyebrow">Human Review Required</span><h2>Proposed editorial change</h2><p className="subdued">{counts}</p>{review.pending_changes.map((change) => <ChangeCard key={change.change_id} change={change} busy={busy} onApprove={onApprove} onReject={onReject} />)}</section>;
  if (review.status === "completed") return <section className="review-panel success"><span className="eyebrow">Review completed</span><h2>Reviewed document ready</h2><p>{counts}. The original PaperForge report remains unchanged.</p>{review.final_docx_available && <a className="primary link-button" href={docxUrl} target="_blank" rel="noopener noreferrer">Download Reviewed DOCX</a>}</section>;
  const message = review.status === "needs_attention" ? "Review needs manual attention before it can continue." : review.status === "processing" ? "Preparing review…" : `Review ${review.status}. The original report remains available.`;
  return <section className="review-panel"><span className="eyebrow">Review status</span><h2>{message}</h2><p className="subdued">{counts}</p>{review.status === "processing" && <button className="secondary" onClick={onRefresh}>Refresh review status</button>}</section>;
}
