"""Tests for deterministic standalone HTML rendering."""

from copy import deepcopy
from uuid import UUID

import pytest

from app.reports import (
    EnhancedResearchReport,
    Finding,
    HTMLRenderer,
    InvalidResearchReportError,
    ReportRenderingError,
    ResearchReport,
    SynthesisMetadata,
    SynthesisSourceEvidence,
    SynthesizedSection,
    TimelineEvent,
)
from app.reports import html_renderer

_CHUNK_ID = UUID("12345678-1234-5678-1234-567812345678")


def _base_report(
    *,
    title: str = "Research Report",
    include_content: bool = True,
) -> ResearchReport:
    """Build a local immutable base-report fixture without network access."""
    if not include_content:
        return ResearchReport(
            title=title,
            executive_summary="Deterministic base summary.",
            findings=(),
            important_entities=(),
            important_definitions=(),
            important_metrics=(),
            timeline=(),
            references=(),
            sections=(),
        )

    return ResearchReport(
        title=title,
        executive_summary="Deterministic base summary.",
        findings=(
            Finding(
                title="Deterministic finding",
                description="The deterministic base finding is not rendered.",
                supporting_chunk_ids=(_CHUNK_ID,),
            ),
        ),
        important_entities=("PaperForge",),
        important_definitions=("Evidence means supporting information.",),
        important_metrics=("95%",),
        timeline=(
            TimelineEvent(
                date="2026-07-29",
                description="Extracted date: 2026-07-29.",
                supporting_chunk_ids=(_CHUNK_ID,),
            ),
        ),
        references=("https://example.com/source",),
        sections=(),
    )


def _enhanced_report(
    *,
    base_report: ResearchReport | None = None,
    include_enhancements: bool = True,
) -> EnhancedResearchReport:
    """Build a valid immutable enhanced-report fixture for HTML rendering."""
    findings: tuple[Finding, ...]
    sections: tuple[SynthesizedSection, ...]
    if include_enhancements:
        findings = (
            Finding(
                title="Grouped backend work",
                description="The source documents API and middleware improvements.",
                supporting_chunk_ids=(_CHUNK_ID,),
            ),
        )
        sections = (
            SynthesizedSection(
                heading="Professional Experience",
                content="The documented work covers backend APIs and middleware.",
                supporting_chunk_ids=(_CHUNK_ID,),
            ),
        )
    else:
        findings = ()
        sections = ()

    return EnhancedResearchReport(
        base_report=base_report or _base_report(),
        executive_summary=(
            "The source describes backend engineering work focused on APIs.\n\n"
            "It records measurable performance improvements from that work."
        ),
        findings=findings,
        sections=sections,
        synthesis_metadata=SynthesisMetadata(
            provider="groq",
            model="test-model",
            elapsed_ms=0.0,
            successful=True,
        ),
    )


def test_html_renderer_produces_stable_self_contained_document() -> None:
    """Repeated rendering emits a complete, standalone HTML document."""
    report = _enhanced_report()
    before = deepcopy(report.model_dump(mode="python"))
    renderer = HTMLRenderer()

    first = renderer.render(report)
    second = renderer.render(report)

    assert first == second
    assert report.model_dump(mode="python") == before
    assert first.startswith("<!doctype html>\n<html lang=\"en\">")
    assert first.endswith("</html>\n")
    assert '<meta charset="utf-8">' in first
    assert '<meta name="viewport" content="width=device-width, initial-scale=1">' in first
    assert '<style id="paperforge-report-styles">' in first
    assert '<style id="paperforge-print-styles" media="print">' in first
    assert "--background: #f7f8fa;" in first
    assert "@page" in first
    assert '<link rel="stylesheet"' not in first
    assert "<script" not in first.lower()
    assert "cdn" not in first.lower()


def test_html_renderer_renders_required_content_in_layout_order() -> None:
    """Enhanced and deterministic report fields appear in the fixed layout."""
    html = HTMLRenderer().render(_enhanced_report())

    expected_text = (
        "Research Report",
        "Executive Summary",
        "Key Findings",
        "Important Entities",
        "Definitions",
        "Metrics",
        "Timeline",
        "References",
        "Professional Experience",
        "Generated By",
        "Generated with PaperForge.",
    )
    positions = [html.index(value) for value in expected_text]

    assert positions == sorted(positions)
    assert "The source describes backend engineering work focused on APIs." in html
    assert "Grouped backend work" in html
    assert "PaperForge" in html
    assert "Evidence means supporting information." in html
    assert "95%" in html
    assert "2026-07-29" in html
    assert "https://example.com/source" in html
    assert "The documented work covers backend APIs and middleware." in html
    assert "Provider" in html and "groq" in html
    assert "Model" in html and "test-model" in html
    assert "Status" in html and "Successful" in html


def test_html_renderer_escapes_dynamic_content() -> None:
    """Jinja autoescaping prevents hostile model strings from becoming markup."""
    hostile = "<script>alert('unsafe')</script>"
    base_report = ResearchReport(
        title=hostile,
        executive_summary="Base summary.",
        findings=(),
        important_entities=(hostile,),
        important_definitions=(),
        important_metrics=(),
        timeline=(),
        references=(),
        sections=(),
    )

    html = HTMLRenderer().render(_enhanced_report(base_report=base_report))

    assert hostile not in html
    assert "&lt;script&gt;alert(&#39;unsafe&#39;)&lt;/script&gt;" in html


def test_html_renderer_renders_empty_collections_with_accessible_empty_states() -> None:
    """Every required collection section remains visible when it has no content."""
    report = _enhanced_report(
        base_report=_base_report(include_content=False),
        include_enhancements=False,
    )

    html = HTMLRenderer().render(report)

    assert html.count("No information was extracted for this section.") == 6
    assert html.count('class="empty-state"') == 6
    for heading in (
        "Key Findings",
        "Important Entities",
        "Definitions",
        "Metrics",
        "Timeline",
        "References",
    ):
        assert heading in html
    assert "Professional Experience" not in html


def test_html_renderer_accepts_any_nonblank_summary_and_rejects_corruption() -> None:
    """Presentation accepts fallback prose while still rejecting malformed models."""
    malformed = EnhancedResearchReport.model_construct(
        base_report=_base_report(),
        executive_summary="Only one paragraph.",
        findings=(),
        sections=(),
        synthesis_metadata=SynthesisMetadata(
            provider="groq",
            model="test-model",
            elapsed_ms=0.0,
            successful=True,
        ),
    )

    assert "Only one paragraph." in HTMLRenderer().render(malformed)
    with pytest.raises(InvalidResearchReportError, match="EnhancedResearchReport"):
        HTMLRenderer().render(object())  # type: ignore[arg-type]

    corrupted_base_report = ResearchReport.model_construct(
        title="Research Report",
        executive_summary="Base summary.",
        findings=(),
        important_entities=("Duplicate", "Duplicate"),
        important_definitions=(),
        important_metrics=(),
        timeline=(),
        references=(),
        sections=(),
    )
    nested_malformed = EnhancedResearchReport.model_construct(
        base_report=corrupted_base_report,
        executive_summary=(
            "First valid paragraph.\n\nSecond valid paragraph."
        ),
        findings=(),
        sections=(),
        synthesis_metadata=SynthesisMetadata(
            provider="groq",
            model="test-model",
            elapsed_ms=0.0,
            successful=True,
        ),
    )

    with pytest.raises(InvalidResearchReportError, match="structural"):
        HTMLRenderer().render(nested_malformed)


def test_html_renderer_renders_a_nullable_model_generically() -> None:
    """A fallback overlay displays no model without provider-specific logic."""
    fallback = EnhancedResearchReport(
        base_report=_base_report(include_content=False),
        executive_summary="Deterministic fallback summary.",
        findings=(),
        sections=(),
        synthesis_metadata=SynthesisMetadata(
            provider="fallback",
            model=None,
            elapsed_ms=0.0,
            successful=True,
            enhanced=False,
            fallback=True,
            reason="timeout",
            source_evidence=(
                SynthesisSourceEvidence(
                    chunk_id=_CHUNK_ID,
                    confidence=1.0,
                    references=(),
                ),
            ),
        ),
    )

    html = HTMLRenderer().render(fallback)

    assert "fallback" in html
    assert "Not applicable" in html
    assert "Deterministic fallback summary." in html


def test_html_renderer_maps_unexpected_template_errors(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """Unexpected Jinja failures never escape the report rendering boundary."""
    def fail_template_load(_: str) -> object:
        raise RuntimeError("template failure")

    monkeypatch.setattr(html_renderer, "get_html_template", fail_template_load)

    with pytest.raises(ReportRenderingError, match="Unable to render"):
        HTMLRenderer().render(_enhanced_report())
