import { useEffect, useRef, useState } from "react";
import { api, PaperForgeApiError } from "./api/client";
import type { ReportMetadata, ReviewState } from "./api/types";
import { UploadPanel } from "./components/UploadPanel";
import { ReportWorkspace } from "./components/ReportWorkspace";

type Connection = "checking" | "connected" | "unavailable";
const reportFromUrl = () => new URLSearchParams(window.location.search).get("report")?.trim() ?? "";
const validReportId = (value: string) => /^[A-Za-z0-9-]+$/.test(value);
const clearReportUrl = () => window.history.replaceState(null, "", window.location.pathname);

export default function App() {
  const [initialReportId] = useState(reportFromUrl); const [files, setFiles] = useState<File[]>([]); const [reportId, setReportId] = useState<string | null>(null); const [metadata, setMetadata] = useState<ReportMetadata | null>(null); const [review, setReview] = useState<ReviewState | null>(null); const [busy, setBusy] = useState(false); const [restoring, setRestoring] = useState(Boolean(initialReportId)); const [connection, setConnection] = useState<Connection>("checking"); const [error, setError] = useState<string | null>(null); const [requestId, setRequestId] = useState<string | null>(null); const started = useRef<number | null>(null); const [elapsed, setElapsed] = useState(0);
  useEffect(() => { api.health().then(() => setConnection("connected")).catch(() => setConnection("unavailable")); }, []);
  useEffect(() => { if (!initialReportId) { setRestoring(false); return; } if (!validReportId(initialReportId)) { clearReportUrl(); setError("That report is no longer available."); setRestoring(false); return; } let active = true; const restore = async () => { try { const restoredMetadata = await api.metadata(initialReportId); if (!active) return; setReportId(initialReportId); setMetadata(restoredMetadata); try { const restoredReview = await api.getReview(initialReportId); if (active) setReview(restoredReview); } catch (caught) { if (!(caught instanceof PaperForgeApiError) || caught.status !== 404) throw caught; } } catch (caught) { if (!active) return; clearReportUrl(); if (caught instanceof PaperForgeApiError && caught.status === 404) setError("That report is no longer available."); else if (caught instanceof PaperForgeApiError) { setError(caught.message); setRequestId(caught.detail.request_id); } else setError("PaperForge is unavailable. Please check the backend connection."); } finally { if (active) setRestoring(false); } }; void restore(); return () => { active = false; }; }, [initialReportId]);
  useEffect(() => { if (started.current === null) return; const timer = window.setInterval(() => setElapsed(Math.floor((Date.now() - started.current!) / 1000)), 1000); return () => window.clearInterval(timer); }, [busy]);
  const safe = async <T,>(work: () => Promise<T>): Promise<T | null> => { setError(null); setRequestId(null); try { return await work(); } catch (caught) { if (caught instanceof PaperForgeApiError) { setError(caught.message); setRequestId(caught.detail.request_id); } else setError("PaperForge is unavailable. Please check the backend connection."); return null; } };
  const generate = async () => { if (!files.length) return; setBusy(true); started.current = Date.now(); setElapsed(0); const created = await safe(() => files.length === 1 ? api.createReport(files[0]) : api.createMultiReport(files)); if (created) { const loaded = await safe(() => api.metadata(created.report_id)); if (loaded) { window.history.replaceState(null, "", `?report=${encodeURIComponent(created.report_id)}`); setReportId(created.report_id); setMetadata(loaded); setReview(null); setFiles([]); } } setBusy(false); started.current = null; };
  const updateReview = async (work: () => Promise<ReviewState>) => { setBusy(true); const next = await safe(work); if (next) setReview(next); setBusy(false); };
  const startNewReport = () => { setFiles([]); setReportId(null); setMetadata(null); setReview(null); setError(null); setRequestId(null); clearReportUrl(); };
  if (restoring) return <div className="app"><header><div className="brand"><strong>PaperForge</strong><span>Grounded document intelligence</span></div></header><main className="restore" aria-live="polite"><span className="eyebrow">Restoring report…</span><p>Loading the persisted report workspace.</p></main></div>;
  return <div className="app"><header><div className="brand"><strong>PaperForge</strong><span>Grounded document intelligence</span></div><div className={`connection ${connection}`}>{connection === "connected" ? "Connected" : connection === "checking" ? "Checking backend" : "Backend unavailable"}</div></header>{error && <div className="error" role="alert">{error}{requestId && <small>Request ID: {requestId}</small>}</div>}{!reportId || !metadata ? <main className="landing"><UploadPanel files={files} onChange={setFiles} onGenerate={generate} busy={busy} />{busy && <aside className="processing" aria-live="polite"><span className="eyebrow">Processing</span><h2>{elapsed < 5 ? "Uploading documents" : elapsed < 15 ? "Analyzing evidence" : elapsed < 30 ? "Building grounded report" : "Preparing publication"}</h2><p>PaperForge is processing your request. This status reflects the current stage of the synchronous workflow, not a percentage.</p><small>{elapsed}s elapsed</small></aside>}</main> : <ReportWorkspace id={reportId} metadata={metadata} review={review} busy={busy} onStart={() => updateReview(() => api.startReview(reportId))} onApprove={(changeId) => updateReview(() => api.approve(reportId, changeId))} onReject={(changeId, feedback) => updateReview(() => api.reject(reportId, changeId, feedback))} onRefresh={() => updateReview(() => api.getReview(reportId))} onNewReport={startNewReport} />}</div>;
}
