import { fireEvent, render, screen } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import App from "./App";

const health = { status: "healthy", service: "PaperForge", version: "0.12.0", ready: true };
const metadata = { report_id: "r-1", status: "completed", available_formats: ["html", "pdf"], document: { filename: "research.pdf", file_type: "PDF", page_count: 2, word_count: 300, character_count: 1000 }, generation: { provider: "groq", model: "test", elapsed_ms: 1, successful: true, fallback: false, enhanced: true, reason: null } };
const project = { id: "r-1", title: "Research", report_id: "r-1", status: "ready", sources: [metadata.document], available_formats: ["html", "pdf"], created_at: "2026-09-08T10:00:00.000Z", updated_at: "2026-09-08T10:00:00.000Z" };
const queuedJob = { job_id: "job-1", report_id: "r-1", status: "queued", stage: "queued", progress: 8, message: "Sources uploaded; waiting to start", source_filenames: ["research.pdf"], provider: null, fallback: null, error: null, created_at: "2026-09-08T10:00:00.000Z", updated_at: "2026-09-08T10:00:00.000Z", completed_at: null };
const completedJob = { ...queuedJob, status: "completed", stage: "completed", progress: 100, message: "Your report is ready", provider: "groq", fallback: false, completed_at: "2026-09-08T10:01:00.000Z" };
const presentation = { cover: { title: "Research", domain: "General Research", generated_on: "2026-09-08", status: "AI-enhanced", author: "Kalpesh Sharma", organisation: null, provider: "groq", model: "test", knowledge_object_count: 2, evidence_source_count: 2, mean_confidence: 0.82 }, template_key: "paperforge-classic", mode: "professional", table_of_contents: { entries: [{ heading: "Abstract", anchor_id: "abstract" }, { heading: "Major Findings", anchor_id: "key-insights" }] }, sections: [{ key: "abstract", heading: "Abstract", anchor_id: "abstract" }, { key: "key-insights", heading: "Major Findings", anchor_id: "key-insights" }] };
const change = { change_id: "ch-1", operation: "edit", chunk_id: "c-1", document_id: "doc-1", old_html: "<p>Before sentence.</p>", new_html: "<p>After sentence.</p>", ai_explanation: "Clearer.", insert_after_chunk_id: null, insert_before_chunk_id: null };
function mockFetch(initialProjects: typeof project[] = []) { const calls: Array<{ url: string; init?: RequestInit }> = []; let projects = [...initialProjects]; vi.stubGlobal("fetch", vi.fn(async (url: string, init?: RequestInit) => { calls.push({ url, init }); if (url.endsWith("/health")) return new Response(JSON.stringify(health)); if ((url.endsWith("/reports/jobs") || url.endsWith("/reports/jobs/multi")) && init?.method === "POST") return new Response(JSON.stringify(queuedJob), { status: 202 }); if (url.endsWith("/reports/r-1/regenerate") && init?.method === "POST") return new Response(JSON.stringify(queuedJob), { status: 202 }); if (url.endsWith("/reports/jobs/job-1")) return new Response(JSON.stringify(completedJob)); if (url.endsWith("/projects") && !init?.method) return new Response(JSON.stringify(projects)); if (url.endsWith("/projects/r-1") && init?.method === "PATCH") { const title = JSON.parse(String(init.body)).title; projects = [{ ...project, title }, ...projects.filter((item) => item.id !== "r-1")]; return new Response(JSON.stringify(projects[0])); } if (url.endsWith("/projects/r-1") && init?.method === "DELETE") { projects = []; return new Response(null, { status: 204 }); } if (url.endsWith("/projects/r-1")) return new Response(JSON.stringify(projects.find((item) => item.id === "r-1") ?? project)); if (url.endsWith("/metadata")) return new Response(JSON.stringify(metadata)); if (url.endsWith("/reports/r-1")) return new Response(JSON.stringify(presentation)); if (url.endsWith("/review") && init?.method === "POST") return new Response(JSON.stringify({ report_id: "r-1", status: "awaiting_approval", pending_changes: [change], approved_changes: [], rejected_changes: [], final_docx_available: false })); if (url.endsWith("/review")) return new Response(JSON.stringify({ error: { code: "not_found", message: "No review yet.", request_id: "test" } }), { status: 404 }); if (url.includes("/approve")) return new Response(JSON.stringify({ report_id: "r-1", status: "completed", pending_changes: [], approved_changes: [change], rejected_changes: [], final_docx_available: true })); return new Response(JSON.stringify({ report_id: "r-1", status: "completed", available_formats: [] })); })); return calls; }

async function reachUploadStep() {
  await userEvent.type(screen.getByLabelText(/Project name/i), "AI Governance Review");
  await userEvent.type(screen.getByLabelText(/Research domain/i), "Artificial Intelligence");
  await userEvent.click(screen.getByRole("button", { name: /Continue/i }));
}

async function reachGenerateStep(files: File[]) {
  await reachUploadStep();
  fireEvent.change(screen.getByLabelText("PDF files input"), { target: { files } });
  await userEvent.click(screen.getByRole("button", { name: /Continue/i }));
  await userEvent.click(screen.getByRole("button", { name: /Technical analysis/i }));
  await userEvent.click(screen.getByRole("button", { name: /Continue/i }));
  await userEvent.click(screen.getByRole("button", { name: /High-contrast typography/i }));
  await userEvent.click(screen.getByRole("button", { name: /Continue/i }));
  await userEvent.click(screen.getByRole("button", { name: /Continue/i }));
  await userEvent.click(screen.getByRole("button", { name: /Continue/i }));
}

beforeEach(() => { window.localStorage.clear(); vi.stubGlobal("scrollTo", vi.fn()); });
afterEach(() => { vi.unstubAllGlobals(); window.history.replaceState(null, "", "/"); });
test("landing page opens the product workspace", async () => { mockFetch(); render(<App />); expect(screen.getByRole("heading", { name: /report worth submitting/i })).toBeInTheDocument(); await userEvent.click(screen.getByRole("button", { name: "Open workspace" })); expect(await screen.findByRole("heading", { name: /Good evening/i })).toBeInTheDocument(); });
test("profile control opens useful workspace actions", async () => { window.history.replaceState(null, "", "/app"); mockFetch(); render(<App />); const profile = screen.getByRole("button", { name: /Kalpesh Personal workspace/i }); expect(profile).toHaveAttribute("aria-expanded", "false"); await userEvent.click(profile); expect(profile).toHaveAttribute("aria-expanded", "true"); expect(screen.getByRole("menu", { name: "Workspace actions" })).toBeInTheDocument(); await userEvent.click(screen.getByRole("menuitem", { name: /PaperForge home/i })); expect(await screen.findByRole("heading", { name: /report worth submitting/i })).toBeInTheDocument(); });
test("one PDF starts a background job, saves a project, and transitions to report workspace", async () => { window.history.replaceState(null, "", "/app/new"); const calls = mockFetch(); render(<App />); const file = new File(["pdf"], "research.pdf", { type: "application/pdf" }); await reachGenerateStep([file]); await userEvent.click(screen.getByRole("button", { name: /Generate report/i })); await screen.findByText("Report ready"); const upload = calls.find((call) => call.url.endsWith("/reports/jobs")); expect(upload?.init?.method).toBe("POST"); expect(upload?.init?.body).toBeInstanceOf(FormData); const form = upload?.init?.body as FormData; expect(form.get("file")).toBe(file); expect(JSON.parse(String(form.get("settings")))).toMatchObject({ project_title: "AI Governance Review", structure: "technical", visual_template: "editorial", author: "Kalpesh Sharma" }); expect(calls.some((call) => call.url.endsWith("/reports/jobs/job-1"))).toBe(true); expect(screen.getByTitle("PaperForge report preview")).toHaveAttribute("src", "http://127.0.0.1:8000/reports/r-1/html"); expect(calls.some((call) => call.url.endsWith("/projects/r-1"))).toBe(true); });
test("project library searches, renames, opens, and deletes saved reports", async () => { window.history.replaceState(null, "", "/app/projects"); mockFetch([{ ...project, title: "Responsible AI" }]); render(<App />); expect(await screen.findByRole("heading", { name: "Responsible AI" })).toBeInTheDocument(); await userEvent.type(screen.getByRole("searchbox", { name: "Search projects" }), "missing"); expect(screen.getByRole("heading", { name: "No matching projects" })).toBeInTheDocument(); await userEvent.clear(screen.getByRole("searchbox", { name: "Search projects" })); await userEvent.click(screen.getByRole("button", { name: "Rename Responsible AI" })); const name = screen.getByRole("textbox", { name: "Report name" }); await userEvent.clear(name); await userEvent.type(name, "AI Governance Review"); await userEvent.click(screen.getByRole("button", { name: "Save" })); expect(await screen.findByRole("heading", { name: "AI Governance Review" })).toBeInTheDocument(); await userEvent.click(screen.getByRole("button", { name: /Open report/i })); expect(await screen.findByText("Report ready")).toBeInTheDocument(); await userEvent.click(screen.getByRole("button", { name: "Projects" })); await userEvent.click(screen.getByRole("button", { name: "Delete AI Governance Review" })); await userEvent.click(screen.getByRole("button", { name: "Delete" })); expect(await screen.findByRole("heading", { name: "No reports yet" })).toBeInTheDocument(); });
test("multiple ordered PDFs use repeated files keys and reject invalid choices", async () => { window.history.replaceState(null, "", "/app/new"); const calls = mockFetch(); render(<App />); await reachUploadStep(); const input = screen.getByLabelText("PDF files input"); fireEvent.change(input, { target: { files: [new File(["x"], "notes.txt", { type: "text/plain" })] } }); expect(screen.getByText("Only PDF files can be selected.")).toBeInTheDocument(); const first = new File(["a"], "a.pdf", { type: "application/pdf" }); const second = new File(["b"], "b.pdf", { type: "application/pdf" }); fireEvent.change(input, { target: { files: [first, second] } }); await userEvent.click(screen.getByRole("button", { name: /Continue/i })); for (let index = 0; index < 4; index += 1) await userEvent.click(screen.getByRole("button", { name: /Continue/i })); await userEvent.click(screen.getByRole("button", { name: /Generate report/i })); await screen.findByText("Report ready"); const form = calls.find((call) => call.url.endsWith("/reports/jobs/multi"))?.init?.body as FormData; expect(form.getAll("files")).toEqual([first, second]); });

test("restores an active background job from its persistent URL", async () => { window.history.replaceState(null, "", "/app/processing?job=job-1"); const calls = mockFetch(); render(<App />); await screen.findByText("Report ready"); expect(calls.some((call) => call.url.endsWith("/reports/jobs/job-1"))).toBe(true); expect(window.location.pathname).toBe("/app/report"); expect(window.localStorage.getItem("paperforge.activeJob")).toBeNull(); });
test("report workspace navigates sections and starts safe regeneration", async () => { window.history.replaceState(null, "", "/app/report?report=r-1"); const calls = mockFetch([project]); render(<App />); await screen.findByRole("navigation", { name: "Report sections" }); await userEvent.click(screen.getByRole("button", { name: /Abstract/i })); expect(screen.getByTitle("PaperForge report preview")).toHaveAttribute("src", "http://127.0.0.1:8000/reports/r-1/html#abstract"); await userEvent.click(screen.getByRole("button", { name: /Regenerate from saved sources/i })); expect(screen.getByText(/current version stays unchanged/i)).toBeInTheDocument(); await userEvent.click(screen.getByRole("button", { name: "Regenerate" })); expect(calls.some((call) => call.url.endsWith("/reports/r-1/regenerate") && call.init?.method === "POST")).toBe(true); });
test("review renders safe text diff and sends only the selected approval", async () => { window.history.replaceState(null, "", "/app/new"); const calls = mockFetch(); render(<App />); const file = new File(["pdf"], "research.pdf", { type: "application/pdf" }); await reachGenerateStep([file]); await userEvent.click(screen.getByRole("button", { name: /Generate report/i })); await screen.findByText("Report ready"); await userEvent.click(screen.getByRole("button", { name: "Review Executive Summary" })); await screen.findByText("Human Review Required"); expect(screen.getByText("Before sentence.")).toBeInTheDocument(); expect(screen.getByText("After sentence.")).toBeInTheDocument(); await userEvent.click(screen.getByRole("button", { name: "Approve change" })); await screen.findByText("Reviewed document ready"); const approve = calls.find((call) => call.url.includes("/approve")); expect(approve?.init?.body).toBe(JSON.stringify({ change_id: "ch-1" })); expect(screen.getByRole("link", { name: "Download Reviewed DOCX" })).toHaveAttribute("href", "http://127.0.0.1:8000/reports/r-1/docx"); });
test("restores a report and review from the URL using GET requests only", async () => { window.history.replaceState(null, "", "/app/report?report=r-1"); const calls: Array<{ url: string; init?: RequestInit }> = []; vi.stubGlobal("fetch", vi.fn(async (url: string, init?: RequestInit) => { calls.push({ url, init }); if (url.endsWith("/health")) return new Response(JSON.stringify(health)); if (url.endsWith("/metadata")) return new Response(JSON.stringify(metadata)); if (url.endsWith("/reports/r-1")) return new Response(JSON.stringify(presentation)); if (url.endsWith("/review")) return new Response(JSON.stringify({ report_id: "r-1", status: "awaiting_approval", pending_changes: [change], approved_changes: [], rejected_changes: [], final_docx_available: false })); return new Response("", { status: 404 }); })); render(<App />); expect(screen.getByText("RESTORING REPORT")).toBeInTheDocument(); await screen.findByText("Human Review Required"); expect(calls.some((call) => call.url.endsWith("/review") && call.init?.method === "POST")).toBe(false); expect(screen.getByRole("link", { name: /Markdown/i })).toHaveAttribute("target", "_blank"); expect(screen.getByRole("link", { name: /HTML page/i })).toHaveAttribute("rel", "noopener noreferrer"); const newReportButtons = screen.getAllByRole("button", { name: "New report" }); await userEvent.click(newReportButtons[newReportButtons.length - 1]); expect(window.location.search).toBe(""); expect(screen.getByRole("heading", { name: "Tell us what you are building" })).toBeInTheDocument(); });
