import { fireEvent, render, screen, waitFor } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import App from "./App";

const health = { status: "healthy", service: "PaperForge", version: "0.12.0", ready: true };
const metadata = { report_id: "r-1", status: "completed", available_formats: ["html", "pdf"], document: { filename: "research.pdf", file_type: "PDF", page_count: 2, word_count: 300, character_count: 1000 }, generation: { provider: "groq", model: "test", elapsed_ms: 1, successful: true, fallback: false, enhanced: true, reason: null } };
const change = { change_id: "ch-1", operation: "edit", chunk_id: "c-1", document_id: "doc-1", old_html: "<p>Before sentence.</p>", new_html: "<p>After sentence.</p>", ai_explanation: "Clearer.", insert_after_chunk_id: null, insert_before_chunk_id: null };
function mockFetch() { const calls: Array<{ url: string; init?: RequestInit }> = []; vi.stubGlobal("fetch", vi.fn(async (url: string, init?: RequestInit) => { calls.push({ url, init }); if (url.endsWith("/health")) return new Response(JSON.stringify(health)); if (url.endsWith("/metadata")) return new Response(JSON.stringify(metadata)); if (url.endsWith("/review") && init?.method === "POST") return new Response(JSON.stringify({ report_id: "r-1", status: "awaiting_approval", pending_changes: [change], approved_changes: [], rejected_changes: [], final_docx_available: false })); if (url.includes("/approve")) return new Response(JSON.stringify({ report_id: "r-1", status: "completed", pending_changes: [], approved_changes: [change], rejected_changes: [], final_docx_available: true })); return new Response(JSON.stringify({ report_id: "r-1", status: "completed", available_formats: [] })); })); return calls; }

afterEach(() => { vi.unstubAllGlobals(); window.history.replaceState(null, "", "/"); });
test("one PDF posts the single upload key and transitions to report workspace", async () => { const calls = mockFetch(); render(<App />); const file = new File(["pdf"], "research.pdf", { type: "application/pdf" }); fireEvent.change(screen.getByLabelText("PDF files input"), { target: { files: [file] } }); await userEvent.click(screen.getByRole("button", { name: "Generate Report" })); await screen.findByText("Report ready"); const upload = calls.find((call) => call.url.endsWith("/reports")); expect(upload?.init?.method).toBe("POST"); expect(upload?.init?.body).toBeInstanceOf(FormData); expect((upload?.init?.body as FormData).get("file")).toBe(file); expect(screen.getByTitle("PaperForge report preview")).toHaveAttribute("src", "http://127.0.0.1:8000/reports/r-1/html"); });
test("multiple ordered PDFs use repeated files keys and reject invalid choices", async () => { const calls = mockFetch(); render(<App />); const input = screen.getByLabelText("PDF files input"); fireEvent.change(input, { target: { files: [new File(["x"], "notes.txt", { type: "text/plain" })] } }); expect(screen.getByText("Only PDF files can be selected.")).toBeInTheDocument(); const first = new File(["a"], "a.pdf", { type: "application/pdf" }); const second = new File(["b"], "b.pdf", { type: "application/pdf" }); fireEvent.change(input, { target: { files: [first, second] } }); await userEvent.click(screen.getByRole("button", { name: "Generate Report" })); await screen.findByText("Report ready"); const form = calls.find((call) => call.url.endsWith("/reports/multi"))?.init?.body as FormData; expect(form.getAll("files")).toEqual([first, second]); });
test("review renders safe text diff and sends only the selected approval", async () => { const calls = mockFetch(); render(<App />); const file = new File(["pdf"], "research.pdf", { type: "application/pdf" }); fireEvent.change(screen.getByLabelText("PDF files input"), { target: { files: [file] } }); await userEvent.click(screen.getByRole("button", { name: "Generate Report" })); await screen.findByText("Report ready"); await userEvent.click(screen.getByRole("button", { name: "Review Executive Summary" })); await screen.findByText("Human Review Required"); expect(screen.getByText("Before sentence.")).toBeInTheDocument(); expect(screen.getByText("After sentence.")).toBeInTheDocument(); await userEvent.click(screen.getByRole("button", { name: "Approve change" })); await screen.findByText("Reviewed document ready"); const approve = calls.find((call) => call.url.includes("/approve")); expect(approve?.init?.body).toBe(JSON.stringify({ change_id: "ch-1" })); expect(screen.getByRole("link", { name: "Download Reviewed DOCX" })).toHaveAttribute("href", "http://127.0.0.1:8000/reports/r-1/docx"); });
test("restores a report and review from the URL using GET requests only", async () => { window.history.replaceState(null, "", "?report=r-1"); const calls: Array<{ url: string; init?: RequestInit }> = []; vi.stubGlobal("fetch", vi.fn(async (url: string, init?: RequestInit) => { calls.push({ url, init }); if (url.endsWith("/health")) return new Response(JSON.stringify(health)); if (url.endsWith("/metadata")) return new Response(JSON.stringify(metadata)); if (url.endsWith("/review")) return new Response(JSON.stringify({ report_id: "r-1", status: "awaiting_approval", pending_changes: [change], approved_changes: [], rejected_changes: [], final_docx_available: false })); return new Response("", { status: 404 }); })); render(<App />); expect(screen.getByText("Restoring report…")).toBeInTheDocument(); await screen.findByText("Human Review Required"); expect(calls.some((call) => call.url.endsWith("/review") && call.init?.method === "POST")).toBe(false); expect(screen.getByRole("link", { name: "Markdown" })).toHaveAttribute("target", "_blank"); expect(screen.getByRole("link", { name: "HTML" })).toHaveAttribute("rel", "noopener noreferrer"); await userEvent.click(screen.getByRole("button", { name: "New report" })); expect(window.location.search).toBe(""); expect(screen.getByRole("button", { name: "Generate Report" })).toBeInTheDocument(); });
